// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// PMCMC_cpp
List PMCMC_cpp(NumericMatrix dataset, NumericMatrix priors, CharacterVector parnames, NumericVector iniPars, NumericMatrix propVar_R, int niter, int npart, double scale, int tol, int nprintsum, int nmultskip, int nupdate, int fixpars, int adapt, IntegerVector iniStates, SEXP func_);
RcppExport SEXP _ABCSMC_PMCMC_cpp(SEXP datasetSEXP, SEXP priorsSEXP, SEXP parnamesSEXP, SEXP iniParsSEXP, SEXP propVar_RSEXP, SEXP niterSEXP, SEXP npartSEXP, SEXP scaleSEXP, SEXP tolSEXP, SEXP nprintsumSEXP, SEXP nmultskipSEXP, SEXP nupdateSEXP, SEXP fixparsSEXP, SEXP adaptSEXP, SEXP iniStatesSEXP, SEXP func_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type dataset(datasetSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type priors(priorsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type parnames(parnamesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type iniPars(iniParsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type propVar_R(propVar_RSEXP);
    Rcpp::traits::input_parameter< int >::type niter(niterSEXP);
    Rcpp::traits::input_parameter< int >::type npart(npartSEXP);
    Rcpp::traits::input_parameter< double >::type scale(scaleSEXP);
    Rcpp::traits::input_parameter< int >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type nprintsum(nprintsumSEXP);
    Rcpp::traits::input_parameter< int >::type nmultskip(nmultskipSEXP);
    Rcpp::traits::input_parameter< int >::type nupdate(nupdateSEXP);
    Rcpp::traits::input_parameter< int >::type fixpars(fixparsSEXP);
    Rcpp::traits::input_parameter< int >::type adapt(adaptSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type iniStates(iniStatesSEXP);
    Rcpp::traits::input_parameter< SEXP >::type func_(func_SEXP);
    rcpp_result_gen = Rcpp::wrap(PMCMC_cpp(dataset, priors, parnames, iniPars, propVar_R, niter, npart, scale, tol, nprintsum, nmultskip, nupdate, fixpars, adapt, iniStates, func_));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ABCSMC_PMCMC_cpp", (DL_FUNC) &_ABCSMC_PMCMC_cpp, 16},
    {NULL, NULL, 0}
};

RcppExport void R_init_ABCSMC(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
