# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

PMCMC_cpp <- function(dataset, priors, parnames, iniPars, propVar_R, niter, npart, scale, nprintsum, nupdate, fixpars, adapt, iniStates, func_) {
    .Call(`_SimBIID_PMCMC_cpp`, dataset, priors, parnames, iniPars, propVar_R, niter, npart, scale, nprintsum, nupdate, fixpars, adapt, iniStates, func_)
}

